// <auto-generated />
using System;
using Demo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Demo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Demo.Models.Agent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Performance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("RunDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TargetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Agents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Company = "Tech Solutions",
                            Name = "John Doe",
                            Performance = 15m,
                            RunDate = new DateTime(2024, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Không Hoạt Động",
                            TargetAmount = 85m
                        },
                        new
                        {
                            Id = 2,
                            Company = "Innovate Inc",
                            Name = "Sarah Miller",
                            Performance = 64m,
                            RunDate = new DateTime(2024, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Hoạt Động",
                            TargetAmount = 92m
                        },
                        new
                        {
                            Id = 3,
                            Company = "Hardware",
                            Name = "Interjohn Phelps",
                            Performance = 54m,
                            RunDate = new DateTime(2024, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Đang Chờ",
                            TargetAmount = 68m
                        },
                        new
                        {
                            Id = 4,
                            Company = "Financial",
                            Name = "David Clark",
                            Performance = 97m,
                            RunDate = new DateTime(2024, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Hoạt Động",
                            TargetAmount = 95m
                        });
                });

            modelBuilder.Entity("Demo.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("Reviews")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Flash Sale",
                            Description = "Áo phông trắng cơ bản, thoải mái và dễ kết hợp",
                            Image = "https://via.placeholder.com/200/ffffff/000000?text=Áo+Phông+Trắng",
                            Name = "Áo Phông Trắng",
                            Price = 199000.0,
                            Rating = 4.7999999999999998,
                            Reviews = 24
                        },
                        new
                        {
                            Id = 2,
                            Category = "Flash Sale",
                            Description = "Quần shorts jean mát mẻ, phù hợp cho mùa hè",
                            Image = "https://via.placeholder.com/200/0066cc/ffffff?text=Quần+Shorts",
                            Name = "Quần Shorts Jean",
                            Price = 299000.0,
                            Rating = 4.9000000000000004,
                            Reviews = 18
                        },
                        new
                        {
                            Id = 3,
                            Category = "Flash Sale",
                            Description = "Áo khoác denim bền bỉ và thời trang",
                            Image = "https://via.placeholder.com/200/663300/ffffff?text=Áo+Khoác",
                            Name = "Áo Khoác Denim",
                            Price = 499000.0,
                            Rating = 4.7000000000000002,
                            Reviews = 32
                        },
                        new
                        {
                            Id = 4,
                            Category = "Flash Sale",
                            Description = "Áo crop top xanh nước biển, trẻ trung và gợi cầm",
                            Image = "https://via.placeholder.com/200/0099ff/ffffff?text=Crop+Top",
                            Name = "Áo Crop Top Xanh",
                            Price = 249000.0,
                            Rating = 5.0,
                            Reviews = 15
                        },
                        new
                        {
                            Id = 5,
                            Category = "Trend Luxe",
                            Description = "Áo vest đen cao cấp, phù hợp cho các sự kiện chính thức",
                            Image = "https://via.placeholder.com/200/333333/ffffff?text=Áo+Vest",
                            Name = "Áo Vest Đen",
                            Price = 799000.0,
                            Rating = 4.9000000000000004,
                            Reviews = 45
                        },
                        new
                        {
                            Id = 6,
                            Category = "Trend Luxe",
                            Description = "Váy trắng dự tiệc elegant, làm nổi bật vẻ đẹp",
                            Image = "https://via.placeholder.com/200/f0f0f0/000000?text=Váy+Trắng",
                            Name = "Váy Trắng Dự Tiệc",
                            Price = 899000.0,
                            Rating = 5.0,
                            Reviews = 38
                        },
                        new
                        {
                            Id = 7,
                            Category = "Trend Luxe",
                            Description = "Áo sơ mi lụa mịn, có phần mềm mại và thoáng khí",
                            Image = "https://via.placeholder.com/200/cccccc/666666?text=Áo+Sơ+Mi",
                            Name = "Áo Sơ Mi Lụa",
                            Price = 699000.0,
                            Rating = 4.7999999999999998,
                            Reviews = 28
                        },
                        new
                        {
                            Id = 8,
                            Category = "Trend Luxe",
                            Description = "Quần tây xám đơn giản, dễ kết hợp với nhiều áo",
                            Image = "https://via.placeholder.com/200/808080/ffffff?text=Quần+Tây",
                            Name = "Quần Tây Xám",
                            Price = 599000.0,
                            Rating = 4.7000000000000002,
                            Reviews = 22
                        },
                        new
                        {
                            Id = 9,
                            Category = "Hot Trend",
                            Description = "Áo len đen ấm áp, thích hợp cho những ngày lạnh",
                            Image = "https://via.placeholder.com/200/1a1a1a/ffffff?text=Áo+Len",
                            Name = "Áo Len Đen",
                            Price = 349000.0,
                            Rating = 4.9000000000000004,
                            Reviews = 51
                        },
                        new
                        {
                            Id = 10,
                            Category = "Hot Trend",
                            Description = "Váy đen midi kinh điển, phù hợp múi lạnh hàng ngày",
                            Image = "https://via.placeholder.com/200/2d2d2d/ffffff?text=Váy+Midi",
                            Name = "Váy Đen Midi",
                            Price = 459000.0,
                            Rating = 4.7999999999999998,
                            Reviews = 42
                        },
                        new
                        {
                            Id = 11,
                            Category = "Hot Trend",
                            Description = "Áo trắng nữ đơn giản nhưng sang trọng",
                            Image = "https://via.placeholder.com/200/ffffff/000000?text=Áo+Trắng",
                            Name = "Áo Trắng Nữ",
                            Price = 249000.0,
                            Rating = 5.0,
                            Reviews = 67
                        },
                        new
                        {
                            Id = 12,
                            Category = "Hot Trend",
                            Description = "Áo đỏ dự tiệc nổi bật, tự tin trong các dịp đặc biệt",
                            Image = "https://via.placeholder.com/200/cc0000/ffffff?text=Áo+Đỏ",
                            Name = "Áo Đỏ Dự Tiệc",
                            Price = 549000.0,
                            Rating = 4.9000000000000004,
                            Reviews = 38
                        },
                        new
                        {
                            Id = 13,
                            Category = "Thời Trang Nam",
                            Description = "Quần jeans nam bền bỉ, dễ mix and match",
                            Image = "https://via.placeholder.com/200/003d7a/ffffff?text=Quần+Jeans",
                            Name = "Quần Jeans Nam",
                            Price = 379000.0,
                            Rating = 4.7999999999999998,
                            Reviews = 55
                        },
                        new
                        {
                            Id = 14,
                            Category = "Thời Trang Nam",
                            Description = "Áo sơ mi nam chất lượng, thích hợp cho công sở",
                            Image = "https://via.placeholder.com/200/ffffff/000000?text=Áo+Sơ+Mi",
                            Name = "Áo Sơ Mi Nam",
                            Price = 299000.0,
                            Rating = 4.7000000000000002,
                            Reviews = 33
                        },
                        new
                        {
                            Id = 15,
                            Category = "Thời Trang Nam",
                            Description = "Áo khoác nam ấm áp và thời trang",
                            Image = "https://via.placeholder.com/200/4d4d4d/ffffff?text=Áo+Khoác",
                            Name = "Áo Khoác Nam",
                            Price = 599000.0,
                            Rating = 4.9000000000000004,
                            Reviews = 48
                        },
                        new
                        {
                            Id = 16,
                            Category = "Thời Trang Nam",
                            Description = "Quần tây nam sang trọng, phù hợp cho các dịp quan trọng",
                            Image = "https://via.placeholder.com/200/333333/ffffff?text=Quần+Tây",
                            Name = "Quần Tây Nam",
                            Price = 449000.0,
                            Rating = 4.7999999999999998,
                            Reviews = 29
                        });
                });

            modelBuilder.Entity("Demo.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
